const OpenAI = require('openai');

const AI_MODEL = process.env.OPENROUTER_MODEL || 'deepseek/deepseek-chat-v3-0324';
let client;

function createServiceError(message) {
  const error = new Error(message);
  error.statusCode = 503;
  return error;
}

function getClient() {
  if (!process.env.OPENROUTER_API_KEY) {
    throw createServiceError('AI service is not configured. Add OPENROUTER_API_KEY on the backend or in Vercel environment variables.');
  }

  if (!client) {
    client = new OpenAI({
      apiKey: process.env.OPENROUTER_API_KEY,
      baseURL: 'https://openrouter.ai/api/v1',
      defaultHeaders: {
        'HTTP-Referer': process.env.CLIENT_URL || process.env.VERCEL_URL || 'http://localhost:5001',
        'X-Title': 'MockAI Interview Prep',
      },
    });
  }

  return client;
}

function toOpenAiMessages(messages = []) {
  return messages
    .slice(-12)
    .filter((message) => message && message.content)
    .map((message) => ({
      role: message.role === 'user' ? 'user' : 'assistant',
      content: String(message.content).slice(0, 3000),
    }));
}

function extractContent(response) {
  const content = response?.choices?.[0]?.message?.content?.trim();
  if (!content) throw createServiceError('AI service returned an empty response. Please try again.');
  return content;
}

function parseJsonObject(raw) {
  const text = String(raw || '').trim();

  try {
    return JSON.parse(text);
  } catch {
    const match = text.match(/\{[\s\S]*\}/);
    if (!match) throw createServiceError('AI feedback was not valid JSON. Please try again.');
    return JSON.parse(match[0]);
  }
}

function normalizeScore(value, fallback = 70) {
  const score = Number(value);
  if (!Number.isFinite(score)) return fallback;
  return Math.max(0, Math.min(100, Math.round(score)));
}

function normalizeArray(value, fallback = []) {
  if (!Array.isArray(value)) return fallback;
  return value.map((item) => String(item)).filter(Boolean).slice(0, 5);
}

function normalizeFeedback(feedback) {
  const confidenceScore = normalizeScore(feedback.confidenceScore);
  const communicationScore = normalizeScore(feedback.communicationScore);
  const technicalScore = normalizeScore(feedback.technicalScore);
  const overallScore = normalizeScore(
    feedback.overallScore,
    Math.round((confidenceScore + communicationScore + technicalScore) / 3)
  );

  return {
    overallScore,
    confidenceScore,
    communicationScore,
    technicalScore,
    strengths: normalizeArray(feedback.strengths, ['Clear effort and interview readiness']),
    improvements: normalizeArray(feedback.improvements, ['Add more specific examples and measurable impact']),
    tips: normalizeArray(feedback.tips, [
      'Answer with a short situation, your action, and the result.',
      'Use numbers when you can.',
      'Connect the answer back to the role.',
    ]),
    summary: String(feedback.summary || 'Feedback generated by MockAI.'),
  };
}

async function generateInterviewResponse({
  jobRole,
  company = 'General',
  interviewType = 'mixed',
  difficulty = 'intermediate',
  messages = [],
} = {}) {
  const history = toOpenAiMessages(messages);
  const hasStarted = history.length > 0;

  const response = await getClient().chat.completions.create({
    model: AI_MODEL,
    temperature: 0.72,
    max_tokens: 420,
    messages: [
      {
        role: 'system',
        content: [
          'You are MockAI, a realistic but supportive interview coach for students and freshers.',
          'Conduct a live mock interview, not a generic chatbot conversation.',
          'Ask one clear question at a time and adapt to the candidate answer.',
          'Keep replies concise: give at most one sentence of coaching, then ask the next question.',
          'Do not invent scores in the chat message. Scores are handled separately.',
          `Role: ${jobRole || 'Software Engineer'}.`,
          `Company context: ${company || 'General'}.`,
          `Interview type: ${interviewType}. Difficulty: ${difficulty}.`,
        ].join('\n'),
      },
      ...history,
      {
        role: 'user',
        content: hasStarted
          ? 'Continue the interview based on the conversation so far. Ask the best next follow-up or next interview question.'
          : 'Start the interview with a short greeting and the first interview question.',
      },
    ],
  });

  return extractContent(response);
}

async function generateInterviewFeedback({
  jobRole,
  answer,
  interviewType = 'mixed',
  difficulty = 'intermediate',
  context = '',
} = {}) {
  const response = await getClient().chat.completions.create({
    model: AI_MODEL,
    temperature: 0.25,
    max_tokens: 520,
    messages: [
      {
        role: 'system',
        content: `Evaluate interview answers for students preparing for real jobs.
Return ONLY valid JSON with this exact shape:
{
  "overallScore": 82,
  "confidenceScore": 80,
  "communicationScore": 84,
  "technicalScore": 78,
  "strengths": ["specific strength"],
  "improvements": ["specific improvement"],
  "tips": ["short actionable tip"],
  "summary": "one short summary"
}`,
      },
      {
        role: 'user',
        content: [
          `Role: ${jobRole || 'Software Engineer'}`,
          `Interview type: ${interviewType}`,
          `Difficulty: ${difficulty}`,
          context ? `Context: ${context}` : '',
          '',
          'Candidate answer:',
          String(answer || '').slice(0, 8000),
        ].join('\n'),
      },
    ],
  });

  return normalizeFeedback(parseJsonObject(extractContent(response)));
}

module.exports = {
  generateInterviewResponse,
  generateInterviewFeedback,
};
