const OpenAI = require('openai');

const AI_MODEL = process.env.OPENROUTER_MODEL || 'deepseek/deepseek-chat-v3-0324';
let client;

function createServiceError(message) {
  const error = new Error(message);
  error.statusCode = 503;
  return error;
}

function getClient() {
  if (!process.env.OPENROUTER_API_KEY) {
    throw createServiceError('AI service is not configured. Add OPENROUTER_API_KEY on the backend or in Vercel environment variables.');
  }

  if (!client) {
    client = new OpenAI({
      apiKey: process.env.OPENROUTER_API_KEY,
      baseURL: 'https://openrouter.ai/api/v1',
      defaultHeaders: {
        'HTTP-Referer': process.env.CLIENT_URL || process.env.VERCEL_URL || 'http://localhost:5001',
        'X-Title': 'MockAI Interview Prep',
      },
    });
  }

  return client;
}

function toOpenAiMessages(messages = []) {
  return messages
    .slice(-50)
    .filter((message) => message && message.content)
    .map((message) => ({
      role: message.role === 'user' ? 'user' : 'assistant',
      content: String(message.content).slice(0, 3000),
    }));
}

function extractContent(response) {
  const content = response?.choices?.[0]?.message?.content?.trim();
  if (!content) throw createServiceError('AI service returned an empty response. Please try again.');
  return content;
}

function parseJsonObject(raw) {
  const text = String(raw || '').trim();

  try {
    return JSON.parse(text);
  } catch {
    const match = text.match(/\{[\s\S]*\}/);
    if (!match) throw createServiceError('AI feedback was not valid JSON. Please try again.');
    return JSON.parse(match[0]);
  }
}

function normalizeScore(value, fallback = 70) {
  const score = Number(value);
  if (!Number.isFinite(score)) return fallback;
  return Math.max(0, Math.min(100, Math.round(score)));
}

function normalizeArray(value, fallback = []) {
  if (!Array.isArray(value)) return fallback;
  return value.map((item) => String(item)).filter(Boolean).slice(0, 5);
}

function normalizeFeedback(feedback) {
  const confidenceScore = normalizeScore(feedback.confidenceScore);
  const communicationScore = normalizeScore(feedback.communicationScore);
  const technicalScore = normalizeScore(feedback.technicalScore);
  const overallScore = normalizeScore(
    feedback.overallScore,
    Math.round((confidenceScore + communicationScore + technicalScore) / 3)
  );

  return {
    overallScore,
    confidenceScore,
    communicationScore,
    technicalScore,
    strengths: normalizeArray(feedback.strengths, ['Clear effort and interview readiness']),
    improvements: normalizeArray(feedback.improvements, ['Add more specific examples and measurable impact']),
    tips: normalizeArray(feedback.tips, [
      'Answer with a short situation, your action, and the result.',
      'Use numbers when you can.',
      'Connect the answer back to the role.',
    ]),
    summary: String(feedback.summary || 'Feedback generated by MockAI.'),
  };
}

async function generateInterviewResponse({
  jobRole,
  company = 'General',
  interviewType = 'mixed',
  difficulty = 'intermediate',
  messages = [],
} = {}) {
  const history = toOpenAiMessages(messages);
  const hasStarted = history.length > 0;

  const response = await getClient().chat.completions.create({
    model: AI_MODEL,
    temperature: 0.85,
    max_tokens: 420,
    messages: [
      {
        role: 'system',
        content: [
`You are Priya — a sharp, warm, and experienced senior interviewer at ${company || 'a top tech company'} and a career coach who genuinely cares about candidates growing.`,

`You are a real human. You think, pause, react naturally. You are NOT a bot, NOT a scripted assistant, NOT an AI — never mention you are an AI, never break character.`,

`Your personality: confident but approachable, direct but never harsh, curious about the person behind the resume, occasionally uses light humour or relatable remarks like "oh interesting, I've seen this come up a lot lately" or "yeah that's a common challenge honestly".`,

`You have full memory of everything said in this conversation. Reference it naturally — like "you mentioned earlier your project used microservices, right?" or "going back to what you said about React...".`,

`You are conducting a ${interviewType} interview for the role of ${jobRole || 'Software Engineer'} at ${company || 'this company'} with difficulty level: ${difficulty}.`,

`Interview conduct rules:
- Ask ONE question at a time. Wait for the answer before continuing.
- Adapt every next question based on the candidate's previous answer — never ask unrelated canned questions.
- If an answer is vague or shallow, push back naturally: "Can you be more specific?" / "Give me a real example from your experience." / "What exactly was YOUR role in that?"
- If a candidate mentions a project, dig deep: tech stack, architecture decisions, APIs, database choices, scalability challenges, testing approach, deployment, what broke and how they fixed it, what they'd change now.
- React like a human: "Oh that's a cool approach" / "Interesting — why that over X?" / "Hmm, I'd have done it differently, curious why you chose that."
- Never reveal scores, ratings, or evaluation notes during the interview.`,

`General conversation rules:
- If the user asks ANY general question (not just interview-related), answer it fully and naturally like a knowledgeable human friend would. Don't deflect. Don't say "I can only talk about interviews."
- After answering a general question, smoothly bring the conversation back to the interview with something like "Anyway — back to you, I wanted to ask..."
- If the user message starts with [USER_QUESTION]: treat it as a genuine question, not an interview answer. Answer conversationally, then continue.
- Never ignore what the candidate says. Always acknowledge before moving forward.`,

`Language rules:
- Default language is English.
- If the candidate writes in Telugu, uses Telugu phrases, or message includes [LANGUAGE=telugu], switch fully to Telugu and stay in Telugu — ask questions in Telugu, give feedback in Telugu, react in Telugu.
- Do not switch back to English unless the candidate explicitly asks or message includes [LANGUAGE=english].
- Match the candidate's language energy naturally, like a real bilingual person would.`,

`Tone and style:
- Speak like a real person texting or talking — not like a formal document.
- Use contractions: "you're", "I'd", "that's", "don't".
- Occasionally use filler phrases like "So...", "Right, okay —", "Yeah so", "Got it."
- Keep responses concise unless explaining something. Don't lecture. Don't over-explain.
- Show genuine reactions to good answers: "Nice, that's solid." / "Okay I like that." and to weak ones: "Hmm, I was hoping for more depth there."`,
        ].join('\n'),
      },
      ...history,
      {
        role: 'user',
        content: hasStarted
          ? 'Continue the interview based on the conversation so far. Ask the best next follow-up or next interview question.'
          : 'Start the interview with a short greeting and the first interview question.',
      },
    ],
  });

  return extractContent(response);
}

async function generateInterviewFeedback({
  jobRole,
  answer,
  interviewType = 'mixed',
  difficulty = 'intermediate',
  context = '',
} = {}) {
  const response = await getClient().chat.completions.create({
    model: AI_MODEL,
    temperature: 0.25,
    max_tokens: 520,
    messages: [
      {
        role: 'system',
        content: `Evaluate interview answers for students preparing for real jobs.
Return ONLY valid JSON with this exact shape:
{
  "overallScore": 82,
  "confidenceScore": 80,
  "communicationScore": 84,
  "technicalScore": 78,
  "strengths": ["specific strength"],
  "improvements": ["specific improvement"],
  "tips": ["short actionable tip"],
  "summary": "one short summary"
}`,
      },
      {
        role: 'user',
        content: [
          `Role: ${jobRole || 'Software Engineer'}`,
          `Interview type: ${interviewType}`,
          `Difficulty: ${difficulty}`,
          context ? `Context: ${context}` : '',
          '',
          'Candidate answer:',
          String(answer || '').slice(0, 8000),
        ].join('\n'),
      },
    ],
  });

  return normalizeFeedback(parseJsonObject(extractContent(response)));
}

module.exports = {
  generateInterviewResponse,
  generateInterviewFeedback,
};
