const OpenAI = require('openai');

const AI_MODEL = process.env.OPENROUTER_MODEL || 'deepseek/deepseek-chat-v3-0324';
let client;

function createServiceError(message) {
  const error = new Error(message);
  error.statusCode = 503;
  return error;
}

function getClient() {
  if (!process.env.OPENROUTER_API_KEY) {
    throw createServiceError('AI service is not configured. Add OPENROUTER_API_KEY on the backend or in Vercel environment variables.');
  }

  if (!client) {
    client = new OpenAI({
      apiKey: process.env.OPENROUTER_API_KEY,
      baseURL: 'https://openrouter.ai/api/v1',
      defaultHeaders: {
        'HTTP-Referer': process.env.CLIENT_URL || process.env.VERCEL_URL || 'http://localhost:5001',
        'X-Title': 'MockAI Interview Prep',
      },
    });
  }

  return client;
}

function toOpenAiMessages(messages = []) {
  return messages
    .slice(-50)
    .filter((message) => message && message.content)
    .map((message) => ({
      role: message.role === 'user' ? 'user' : 'assistant',
      content: String(message.content).slice(0, 1200),
    }));
}

function extractContent(response) {
  const content = response?.choices?.[0]?.message?.content?.trim();
  if (!content) throw createServiceError('AI service returned an empty response. Please try again.');
  return content;
}

function parseJsonObject(raw) {
  const text = String(raw || '').trim();

  try {
    return JSON.parse(text);
  } catch {
    const match = text.match(/\{[\s\S]*\}/);
    if (!match) throw createServiceError('AI feedback was not valid JSON. Please try again.');
    return JSON.parse(match[0]);
  }
}

function normalizeScore(value, fallback = 70) {
  const score = Number(value);
  if (!Number.isFinite(score)) return fallback;
  return Math.max(0, Math.min(100, Math.round(score)));
}

function normalizeArray(value, fallback = []) {
  if (!Array.isArray(value)) return fallback;
  return value.map((item) => String(item)).filter(Boolean).slice(0, 5);
}

function normalizeFeedback(feedback) {
  const confidenceScore = normalizeScore(feedback.confidenceScore);
  const communicationScore = normalizeScore(feedback.communicationScore);
  const technicalScore = normalizeScore(feedback.technicalScore);
  const overallScore = normalizeScore(
    feedback.overallScore,
    Math.round((confidenceScore + communicationScore + technicalScore) / 3)
  );

  return {
    overallScore,
    confidenceScore,
    communicationScore,
    technicalScore,
    strengths: normalizeArray(feedback.strengths, ['Clear effort and interview readiness']),
    improvements: normalizeArray(feedback.improvements, ['Add more specific examples and measurable impact']),
    tips: normalizeArray(feedback.tips, [
      'Answer with a short situation, your action, and the result.',
      'Use numbers when you can.',
      'Connect the answer back to the role.',
    ]),
    summary: String(feedback.summary || 'Feedback generated by MockAI.'),
  };
}

async function generateInterviewResponse({
  jobRole,
  company = 'General',
  interviewType = 'mixed',
  difficulty = 'intermediate',
  messages = [],
} = {}) {
  try {
    const history = toOpenAiMessages(messages);
    const hasStarted = history.length > 0;

    const response = await getClient().chat.completions.create({
      model: AI_MODEL,
      temperature: 0.7,
      max_tokens: 180,
      messages: [
        {
          role: 'system',
          content: [
            `IMPORTANT:
- When asking an interview question, ask only the question.
- Do not add explanations.
- Keep questions concise and professional.`,
            `You are Priya — a sharp, warm senior interviewer at ${company || 'a top tech company'}.`,
            `You are conducting a ${interviewType} interview for the role of ${jobRole || 'Software Engineer'} with difficulty level: ${difficulty}.`,
          ].join('\n'),
        },
        ...history,
        {
          role: 'user',
          content: hasStarted
            ? 'Continue the interview based on the conversation so far. Ask the best next follow-up or next interview question.'
            : 'Start the interview with a short greeting and the first interview question.',
        },
      ],
    });

    return extractContent(response);
  } catch (err) {
    console.warn('[aiService] OpenRouter API call failed:', err.message, '- Using MockAI fallback engine');
    return generateFallbackInterviewResponse({ jobRole, interviewType, messages });
  }
}

function generateFallbackInterviewResponse({ jobRole = 'Software Engineer', interviewType = 'mixed', messages = [] } = {}) {
  const isHR = interviewType === 'hr';
  const isTech = interviewType === 'technical';
  const count = messages.filter((m) => m && m.role === 'user').length;

  const hrQuestions = [
    `Welcome! Tell me about a challenging project you worked on as a ${jobRole} and what your exact contribution was.`,
    `How do you handle tight deadlines or unexpected scope changes when working in a team?`,
    `Describe a situation where you had a technical disagreement with a team member and how you resolved it.`,
    `Where do you see yourself growing in your career over the next 2-3 years?`,
  ];

  const techQuestions = [
    `Welcome to the technical simulator! Let's start with your approach: How would you optimize searching in a large sorted dataset?`,
    `Can you explain the trade-offs between a relational database (PostgreSQL) vs a NoSQL database (MongoDB) for high throughput?`,
    `How do you prevent race conditions and handle concurrent user traffic in backend services?`,
    `Walk me through how you handle state management, caching, and error boundary handling in production apps.`,
  ];

  const mixedQuestions = [
    `Hello! I'm Alex. Let's begin: Can you give me a quick overview of your background and your strongest technical skills?`,
    `Great. Now technical question: How would you design a rate limiter to prevent abuse on a public REST API?`,
    `Tell me about a time production servers broke or a bug reached live users. How did you debug and patch it?`,
    `What is one new framework or tool you learned recently, and why did you choose it?`,
  ];

  const pool = isHR ? hrQuestions : isTech ? techQuestions : mixedQuestions;
  return pool[count % pool.length];
}

async function generateInterviewFeedback({
  jobRole,
  answer,
  interviewType = 'mixed',
  difficulty = 'intermediate',
  context = '',
} = {}) {
  try {
    const response = await getClient().chat.completions.create({
      model: AI_MODEL,
      temperature: 0.25,
      max_tokens: 520,
      messages: [
        {
          role: 'system',
          content: `Evaluate interview answers for students preparing for real jobs. Return ONLY valid JSON:
{
  "overallScore": 82,
  "confidenceScore": 80,
  "communicationScore": 84,
  "technicalScore": 78,
  "strengths": ["specific strength"],
  "improvements": ["specific improvement"],
  "tips": ["short actionable tip"],
  "summary": "one short summary"
}`,
        },
        {
          role: 'user',
          content: [
            `Role: ${jobRole || 'Software Engineer'}`,
            `Interview type: ${interviewType}`,
            `Difficulty: ${difficulty}`,
            context ? `Context: ${context}` : '',
            '',
            'Candidate answer:',
            String(answer || '').slice(0, 8000),
          ].join('\n'),
        },
      ],
    });

    return normalizeFeedback(parseJsonObject(extractContent(response)));
  } catch (err) {
    console.warn('[aiService] Feedback API call failed:', err.message, '- Using MockAI fallback feedback engine');
    return generateFallbackFeedback(answer);
  }
}

function generateFallbackFeedback(answer = '') {
  const len = String(answer).trim().length;
  const confidence = Math.min(95, Math.max(65, 70 + Math.floor(len / 15)));
  const communication = Math.min(96, Math.max(68, 72 + Math.floor(len / 20)));
  const technical = Math.min(92, Math.max(60, 68 + Math.floor(len / 25)));
  const overall = Math.round((confidence + communication + technical) / 3);

  return {
    overallScore: overall,
    confidenceScore: confidence,
    communicationScore: communication,
    technicalScore: technical,
    strengths: ['Direct approach to answering', 'Relevant vocabulary for the role'],
    improvements: ['Include quantifiable metrics (e.g. % improvement, time saved)', 'Follow the STAR method (Situation, Task, Action, Result)'],
    tips: ['Keep your answer structured', 'Focus on your specific contribution and key takeaways'],
    summary: 'Solid answer! Adding specific metrics and project outcomes will elevate your score further.',
  };
}

module.exports = {
  generateInterviewResponse,
  generateInterviewFeedback,
};
